/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.opensymphony.able.apt;

import com.opensymphony.able.entity.*;
import com.sun.mirror.apt.AnnotationProcessorEnvironment;
import com.sun.mirror.apt.Filer.Location;
import com.sun.mirror.declaration.ClassDeclaration;
import com.sun.mirror.util.SimpleDeclarationVisitor;

import org.apache.velocity.Template;
import org.apache.velocity.VelocityContext;
import org.apache.velocity.app.Velocity;

import javax.persistence.Entity;

import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Properties;

/**
 * 
 * @version $Revision: 11 $
 */
public class EntityPropertiesFileClassVisitor extends SimpleDeclarationVisitor {
	private final AnnotationProcessorEnvironment env;

	private Properties entities = new Properties();

	public EntityPropertiesFileClassVisitor(
			final AnnotationProcessorEnvironment env) {
		this.env = env;
	}

	public void visitClassDeclaration(ClassDeclaration declaration) {
		if (matchesDeclaration(declaration)) {
			entities.setProperty(declaration.getQualifiedName(), declaration
					.getSimpleName());
		}
	}

	protected boolean matchesDeclaration(ClassDeclaration declaration) {
		Entity annotation = declaration.getAnnotation(Entity.class);
		return annotation != null;
	}

	public void writeFile(AbleAnnotationProcessor processor) {
		OutputStream out = null;
		try {
			out = env.getFiler().createBinaryFile(Location.SOURCE_TREE, "",
					new File("META-INF/services/able/entities.properties"));
		} catch (Exception e) {
			throw new RuntimeException("Failed to create file: " + e, e);
		}
		try {
			entities.store(out, "JPA Entity Beans auto-generated by Able");
		} catch (IOException e) {
			throw new RuntimeException(
					"Failed to write entity properties file: " + e, e);
		} finally {
			if (out != null) {
				try {
					out.close();
				} catch (IOException e) {
					// ignore
				}
			}
		}
	}
}
