/**
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.opensymphony.able.jaxb;

import com.opensymphony.able.model.Attachment;
import com.opensymphony.able.model.Bug;
import com.opensymphony.able.model.Build;
import com.opensymphony.able.model.Component;
import com.opensymphony.able.model.Person;
import com.opensymphony.able.model.Team;
import com.opensymphony.able.model.User;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;

/**
 * <b>NOTE</b> This file is auto-generated by the Able Maven Plugin
 *
 * Do not edit!
 */
@XmlRootElement(name = "envelope")
public class Envelope extends EnvelopeSupport {

    private List<Attachment> attachmentList;
    private List<Bug> bugList;
    private List<Build> buildList;
    private List<Component> componentList;
    private List<Person> personList;
    private List<Team> teamList;
    private List<User> userList;

    @Override
    public void visit(Closure closure) {
        closure.call(attachmentList);
        closure.call(bugList);
        closure.call(buildList);
        closure.call(componentList);
        closure.call(personList);
        closure.call(teamList);
        closure.call(userList);
    }

    // Properties

    @XmlElement(name = "attachment")
    public List<Attachment> getAttachmentList() {
        return attachmentList;
    }

    public void setAttachmentList(List<Attachment> attachmentList) {
        this.attachmentList = attachmentList;
    }

    @XmlElement(name = "bug")
    public List<Bug> getBugList() {
        return bugList;
    }

    public void setBugList(List<Bug> bugList) {
        this.bugList = bugList;
    }

    @XmlElement(name = "build")
    public List<Build> getBuildList() {
        return buildList;
    }

    public void setBuildList(List<Build> buildList) {
        this.buildList = buildList;
    }

    @XmlElement(name = "component")
    public List<Component> getComponentList() {
        return componentList;
    }

    public void setComponentList(List<Component> componentList) {
        this.componentList = componentList;
    }

    @XmlElement(name = "person")
    public List<Person> getPersonList() {
        return personList;
    }

    public void setPersonList(List<Person> personList) {
        this.personList = personList;
    }

    @XmlElement(name = "team")
    public List<Team> getTeamList() {
        return teamList;
    }

    public void setTeamList(List<Team> teamList) {
        this.teamList = teamList;
    }

    @XmlElement(name = "user")
    public List<User> getUserList() {
        return userList;
    }

    public void setUserList(List<User> userList) {
        this.userList = userList;
    }

}
